"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { motion } from "framer-motion";
import axios from "axios";
import InteractiveGrid from "@/components/InteractiveGrid";

export default function ResultPage() {
  const { id } = useParams();
  const router = useRouter();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    axios.get(`/api/hole/${id}`)
      .then(res => {
        setData(res.data);
        setLoading(false);
      })
      .catch(err => {
        console.error(err);
        setLoading(false);
      });
  }, [id]);

  if (loading) {
    return <div className="min-h-screen bg-zinc-950" />;
  }

  if (!data) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-zinc-950 text-zinc-50">
        <h2 className="text-2xl text-red-400 mb-4">Rabbit hole not found.</h2>
        <button onClick={() => router.push("/")} className="px-6 py-2 bg-white text-black rounded-full font-semibold">
          Go Back
        </button>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen flex-col items-center bg-[#fbf5eb] p-8 pt-24 font-sans text-black relative overflow-hidden">
      {/* Interactive Hover Grid Background */}
      <InteractiveGrid />

      <motion.div 
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="w-full max-w-3xl bg-white border-2 border-black rounded-3xl p-8 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] relative"
      >
        {/* Top Navigation */}
        <button 
          onClick={() => router.push("/")} 
          className="fixed top-8 left-8 flex items-center gap-2 px-6 py-3 bg-teal-300 border-2 border-black rounded-xl text-lg font-black uppercase text-black hover:translate-y-[2px] hover:translate-x-[2px] shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] transition-all z-50"
        >
          <svg className="w-6 h-6 font-bold" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to Warren
        </button>

        <div className="w-full h-48 md:h-64 relative rounded-2xl overflow-hidden mb-8 border-2 border-black bg-rose-400 flex items-center justify-center p-8 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
          <h1 className="text-4xl md:text-5xl font-black text-black uppercase text-center drop-shadow-[2px_2px_0px_rgba(255,255,255,1)] leading-tight">
            {data.topic}
          </h1>
        </div>
        
        {/* Audio Player */}
        {data.audioUrl && (
          <div className="w-full bg-yellow-300 p-6 rounded-2xl mb-12 border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-4 mb-4">
              <div className="w-14 h-14 bg-purple-400 border-2 border-black rounded-full flex items-center justify-center shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                <svg className="w-6 h-6 text-black" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={3}>
                   <path strokeLinecap="round" strokeLinejoin="round" d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
                </svg>
              </div>
              <div>
                <p className="font-black text-black text-xl uppercase">Rabbit Hole Mini-Podcast</p>
                <p className="text-lg font-bold text-black/70">Generated by Gemma & ElevenLabs</p>
              </div>
            </div>
            
            <audio controls className="w-full h-12 outline-none border-2 border-black rounded-full" src={data.audioUrl}>
              Your browser does not support the audio element.
            </audio>
          </div>
        )}

        {/* Summary Content */}
        <div className="prose prose-lg max-w-none">
          <h3 className="text-2xl font-black mb-4 text-black uppercase bg-rose-400 inline-block px-4 py-2 border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] -skew-x-6">The Script</h3>
          <p className="text-xl text-black font-medium leading-relaxed mb-12 italic border-l-8 border-black pl-6 bg-purple-200 p-6 rounded-r-2xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            "{data.script}"
          </p>
          
          <h3 className="text-2xl font-black mb-4 text-black uppercase bg-teal-300 inline-block px-4 py-2 border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] -skew-x-6">The Facts</h3>
          <div className="text-xl font-bold text-black leading-relaxed whitespace-pre-wrap mb-12 bg-yellow-100 p-6 border-2 border-black rounded-2xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            {data.summary}
          </div>

          {/* Go Deeper Buttons */}
          {data.followUps && data.followUps.length > 0 && (
            <div className="mt-12 border-t-4 border-black pt-12">
              <h3 className="text-3xl font-black mb-8 text-black uppercase text-center drop-shadow-[2px_2px_0px_rgba(0,0,0,0.2)]">Go Deeper...</h3>
              <div className="flex flex-col gap-4">
                {data.followUps.map((followUp: string, i: number) => {
                  const colors = ["bg-orange-300", "bg-purple-400", "bg-rose-400"];
                  const bgColor = colors[i % colors.length];
                  return (
                    <button
                      key={i}
                      onClick={() => router.push(`/explore?topic=${encodeURIComponent(followUp)}`)}
                      className={`text-left w-full p-6 rounded-2xl ${bgColor} border-4 border-black text-xl font-black uppercase text-black hover:translate-y-[2px] hover:translate-x-[2px] shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] transition-all group`}
                    >
                      <span className="text-black mr-3 font-bold group-hover:translate-x-2 inline-block transition-transform">↳</span>
                      {followUp}
                    </button>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
}
